AWSTemplateFormatVersion: "2010-09-09"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Export VPC Stack Name"
        Parameters:
          - ExportVPCStackName
      -
        Label:
          default: "Export Security Stack Name"
        Parameters:
          - ExportSecurityStackName
      -
        Label:
         default: "KEY PAIR"
        Parameters:
          - myKeyPair
      -
        Label:
          Default: "Environment Type"
        Parameters:
          - EnvironmentType

Parameters:
  ExportVPCStackName:
    Description: Add the VPC name here
    Type: String

  ExportSecurityStackName:
    Description: Add the Security name here
    Type: String

  myKeyPair:
    Description: Please select a Key Pair.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: You must select a Key Pair.

  EnvironmentType: 
    Description: The environment type
    Type: String
    Default: test
    AllowedValues: 
      - prod
      - test
    ConstraintDescription: must be a prod or test
  
Mappings: 
  RegionMap: 
    us-east-1:
      test: ami-0ff8a91507f77f867
      prod: ami-0a584ac55a7631c0c
    us-west-1:
      test: ami-0bdb828fd58c52235
      prod: ami-066ee5fd4a9ef77f1
    eu-west-1:
      test: ami-047bb4163c506cd98
      prod: ami-0a7c483d527806435
    ap-northeast-1:
      test: ami-06cd52961ce9f0d85
      prod: ami-053cdd503598e4a9d
    ap-southeast-1:
      test: ami-08569b978cc4dfa10
      prod: ami-0be9df32ae9f92309

Resources:
  myEC2PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", !Ref EnvironmentType]
      InstanceType: t2.micro
      KeyName: 
        Ref: myKeyPair
      SubnetId:
        Fn::ImportValue: 
          !Sub ${ExportVPCStackName}-myPrivateSubnetOne
      #  Ref: myPrivateSubnetOne
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportSecurityStackName}-myPrivateSecurityGroup
        #- Ref: myPrivateSecurityGroup

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", !Ref EnvironmentType]
      InstanceType: t2.micro
      KeyName:
        Ref: myKeyPair
      SubnetId:
        Fn::ImportValue: 
          !Sub ${ExportVPCStackName}-myPublicSubnetOne
        #Ref: myPublicSubnetOne
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportSecurityStackName}-mySecurityGroup
       # - Ref: mySecurityGroup

  myEIP:
    Type: AWS::EC2::EIP  # Allocate an Elastic IP address
    Properties:
      InstanceId: 
        Ref: myEC2Instance