AWSTemplateFormatVersion: "2010-09-09"



Parameters:
  ExportVPCStackName:
    Description: Add the VPC name here
    Type: String

  ExportSecurityStackName:
    Description: Add the Security name here
    Type: String

  myKeyPair:
    Description: Please select a Key Pair.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: You must select a Key Pair.

Resources:
  myEC2PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9  
      InstanceType: t2.micro
      KeyName: 
        Ref: myKeyPair
      SubnetId:
        Fn::ImportValue: 
          !Sub ${ExportVPCStackName}-myPrivateSubnetOne
      #  Ref: myPrivateSubnetOne
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportSecurityStackName}-myPrivateSecurityGroup
        #- Ref: myPrivateSecurityGroup

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9  
      InstanceType: t2.micro
      KeyName:
        Ref: myKeyPair
      SubnetId:
        Fn::ImportValue: 
          !Sub ${ExportVPCStackName}-myPublicSubnetOne
        #Ref: myPublicSubnetOne
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportSecurityStackName}-mySecurityGroup
       # - Ref: mySecurityGroup

  myEIP:
    Type: AWS::EC2::EIP  # Allocate an Elastic IP address
    Properties:
      InstanceId: 
        Ref: myEC2Instance